version: '3'

services:
  ssr:
    build: ./shadowsocksR
    ports:
      - '51348:51348'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - ‘/var/log/shadowsocksr.log:/var/log/shadowsocksr.log'
    command: python server.py -p 51348 -k fuckinggfw -m aes-128-ctr -O auth_aes128_md5 -o tls1.2_ticket_auth -G 32
  shadowsocks:
    build: .
    ports:
      - '443:443'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    command: ss-server -s 0.0.0.0 -p 443 -k fuckinggfw -m aes-256-cfb