version: '3'

services:
  ssr:
    build: ./shadowsocksR
    ports:
      - '51348:51348'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
  shadowsocks:
    build: .
    ports:
      - '443:443'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    command: ss-server -s 0.0.0.0 -p 443 -k fuckinggfw -m aes-256-cfb