version: '3'

services:
  shadowsocks:
    image: esme518/docker-shadowsocksr
    ports:
      - '8388:8388'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    command: ssserver -s 0.0.0.0 -p 8388 -k fuckinggfw -m aes-128-ctr -O auth_aes128_md5 -o tls1.2_ticket_auth_compatible -t tls1.2_ticket_auth_compatible -G 32
  shadowsocks:
    build: .
    ports:
      - '443:443'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    command: ss-server -s 0.0.0.0 -p 443 -k fuckinggfw -m aes-256-cfb