version: '3'

services:
  ssr:
    build: ./shadowsocksR
    ports:
      - '19891:19891'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    command: python server.py -p 19891 -k fuckinggfw -m aes-128-ctr -O auth_aes128_md5 -o tls1.2_ticket_auth_compatible -G 32
  shadowsocks:
    build: .
    ports:
      - '443:443'
    restart: always
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    command: ss-server -s 0.0.0.0 -p 443 -k fuckinggfw -m aes-256-cfb